# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tdb < Formula
  desc "TUI database client for PostgreSQL, MySQL, SQLite, and SQL Server"
  homepage "https://github.com/mineee1102/tdb"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mineee1102/tdb/releases/download/v0.1.0/tdb_0.1.0_darwin_amd64.tar.gz"
      sha256 "ac258b9f52efb57ec12a16743b8bf364274b6daecc33fea37ea78a3f02c52434"

      define_method(:install) do
        bin.install "tdb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mineee1102/tdb/releases/download/v0.1.0/tdb_0.1.0_darwin_arm64.tar.gz"
      sha256 "fc983f206f45e2bdb73fde493c532b6962803b1eac35af6e1c0c79e2dc8c7acd"

      define_method(:install) do
        bin.install "tdb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mineee1102/tdb/releases/download/v0.1.0/tdb_0.1.0_linux_amd64.tar.gz"
      sha256 "920457034817ad42da5f1d2e6720c53b2e34ae778300cb79bd85227990a1e40f"
      define_method(:install) do
        bin.install "tdb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mineee1102/tdb/releases/download/v0.1.0/tdb_0.1.0_linux_arm64.tar.gz"
      sha256 "bdddc20f7f91147ce4277a186e3c4e2e05ecf4b91dcbd9be530b4cc3c1013a70"
      define_method(:install) do
        bin.install "tdb"
      end
    end
  end

  test do
    system "#{bin}/tdb", "--version"
  end
end
